### ISSUE TITLE
Cleaning up sample study data

### ISSUE THREAD

**Issue by Unberath** [buschlab/MIRACUM-cbioportal#51]
Right now we do have two studies 'testpatient' and 'patient_example'. 
It would be great to declutter and if necessary combine them to one study (if they showcase different types of data).

**Comment by nr23730** [comment]
tl;dr I see a reason to still have the Patient_example dataset, but some cleanup would be nice.

Patient_example contains mutation and cna data from https://github.com/AG-Boerries/MIRACUM-Pipe. This probably needs an update due to the lastest changes in the pipeline. But in general I would like to keep this up for all other partner sites so that they can verify that the pipeline is deployed correctly, since the external quality assessment is not fully established yet.
This means also that most of the clinical attributes could be removed from `Patient_example`.

**Comment by Unberath** [comment]
I see your point and I already assumed something like that.
We should then probably remove the duplicate clinical sample data and clarify somewhere that the study represents test data from MIRACUM pipe, for instance by renaming the study.

**Comment by nr23730** [comment]
fixed with #55
